-- ============================================================
-- AI 주식 자동매매 시스템 - Database Schema (AUTO-GENERATED)
-- PostgreSQL 16
--
-- ⚠️  이 파일은 자동 생성됩니다. 직접 편집하지 마세요.
--     스키마 소스: api-server/src/main/resources/db/changelog/ (Liquibase)
--     재생성:      ./database/generate-schema.sh
--     사람용 설명/ERD: database/README.md
-- ============================================================

--
-- PostgreSQL database dump
--

\restrict GiVCyOciIMcYY1xDyKq1bvB8cUdwqOIQUnYCVWQMVfGNZtkkUH5az1TBtuHb5go

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_trade_decision; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_trade_decision (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    decision_date date NOT NULL,
    decision character varying(10) NOT NULL,
    rank integer,
    reason text,
    prompt_summary text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    confidence_score numeric(5,4),
    feature_summary jsonb
);


--
-- Name: TABLE ai_trade_decision; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ai_trade_decision IS 'Gemini AI 매매 판단 결과';


--
-- Name: COLUMN ai_trade_decision.confidence_score; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ai_trade_decision.confidence_score IS 'Gemini 판단 신뢰도 (0.0~1.0, 추후 확장용)';


--
-- Name: COLUMN ai_trade_decision.feature_summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ai_trade_decision.feature_summary IS '판단 근거 주요 피처값 요약';


--
-- Name: ai_trade_decision_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_trade_decision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_trade_decision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_threshold_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feature_threshold_config (
    id integer NOT NULL,
    feature_name character varying(50) NOT NULL,
    buy_enabled boolean DEFAULT true,
    buy_operator character varying(10),
    buy_threshold numeric(20,8),
    buy_description text,
    sell_enabled boolean DEFAULT true,
    sell_operator character varying(10),
    sell_threshold numeric(20,8),
    sell_description text,
    is_active boolean DEFAULT true,
    updated_at timestamp without time zone DEFAULT now(),
    updated_by character varying(50) DEFAULT 'SYSTEM'::character varying
);


--
-- Name: feature_threshold_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feature_threshold_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_threshold_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: market_daily_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_daily_summary (
    id bigint NOT NULL,
    summary_date date NOT NULL,
    kospi_index numeric(10,2),
    kospi_change_rate numeric(6,2),
    kospi_volume bigint,
    total_stocks integer,
    rising_stocks integer,
    falling_stocks integer,
    unchanged_stocks integer,
    total_foreign_net_buy bigint,
    total_institutional_net_buy bigint,
    market_sentiment_score numeric(5,3),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE market_daily_summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.market_daily_summary IS '시장 전체 일일 요약 데이터';


--
-- Name: COLUMN market_daily_summary.kospi_index; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.market_daily_summary.kospi_index IS 'KOSPI 지수';


--
-- Name: COLUMN market_daily_summary.kospi_change_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.market_daily_summary.kospi_change_rate IS 'KOSPI 변화율(%)';


--
-- Name: COLUMN market_daily_summary.kospi_volume; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.market_daily_summary.kospi_volume IS 'KOSPI 거래량';


--
-- Name: COLUMN market_daily_summary.market_sentiment_score; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.market_daily_summary.market_sentiment_score IS '시장 전반 뉴스 감성 점수';


--
-- Name: market_daily_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.market_daily_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_daily_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_analysis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_analysis (
    id bigint NOT NULL,
    stock_code character varying(10),
    analysis_date date NOT NULL,
    sentiment_score numeric(5,3) NOT NULL,
    news_count integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE news_analysis; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.news_analysis IS 'KR-FinBERT 감성 분석 결과';


--
-- Name: news_analysis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_analysis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_analysis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prophet_forecast; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prophet_forecast (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    forecast_date date NOT NULL,
    yhat_d1 numeric(12,2),
    yhat_d2 numeric(12,2),
    yhat_d3 numeric(12,2),
    yhat_d4 numeric(12,2),
    yhat_d5 numeric(12,2),
    yhat_upper_d1 numeric(12,2),
    yhat_upper_d2 numeric(12,2),
    yhat_upper_d3 numeric(12,2),
    yhat_upper_d4 numeric(12,2),
    yhat_upper_d5 numeric(12,2),
    yhat_lower_d1 numeric(12,2),
    yhat_lower_d2 numeric(12,2),
    yhat_lower_d3 numeric(12,2),
    yhat_lower_d4 numeric(12,2),
    yhat_lower_d5 numeric(12,2),
    price_trend numeric(10,6),
    volume_trend numeric(10,6),
    price_uncertainty numeric(10,4),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE prophet_forecast; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.prophet_forecast IS 'Prophet D+1~D+5 시계열 예측 결과';


--
-- Name: prophet_forecast_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prophet_forecast ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prophet_forecast_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    revoked_at timestamp without time zone
);


--
-- Name: TABLE refresh_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.refresh_tokens IS 'JWT 리프레시 토큰 관리';


--
-- Name: COLUMN refresh_tokens.revoked_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.refresh_tokens.revoked_at IS '토큰 무효화 시각';


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: safety_filter_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.safety_filter_result (
    id integer NOT NULL,
    filter_date date NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(100),
    passed boolean DEFAULT false NOT NULL,
    failure_reason text,
    max_quantity integer,
    current_price bigint,
    filter_checks jsonb,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: TABLE safety_filter_result; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.safety_filter_result IS 'Stage 4 안전장치 필터링 결과';


--
-- Name: COLUMN safety_filter_result.filter_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.filter_date IS '필터링 수행 날짜';


--
-- Name: COLUMN safety_filter_result.stock_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.stock_code IS '종목 코드';


--
-- Name: COLUMN safety_filter_result.stock_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.stock_name IS '종목명';


--
-- Name: COLUMN safety_filter_result.passed; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.passed IS '필터 통과 여부';


--
-- Name: COLUMN safety_filter_result.failure_reason; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.failure_reason IS '필터 미통과 사유';


--
-- Name: COLUMN safety_filter_result.max_quantity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.max_quantity IS '투자금액 기준 최대 매수 가능 수량';


--
-- Name: COLUMN safety_filter_result.current_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.current_price IS '필터링 시점의 현재가';


--
-- Name: COLUMN safety_filter_result.filter_checks; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_filter_result.filter_checks IS '각 규칙별 통과 여부 JSON';


--
-- Name: safety_filter_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.safety_filter_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.safety_filter_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_filter_score; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_filter_score (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    score_date date NOT NULL,
    foreign_net_buy bigint NOT NULL,
    institutional_net_buy bigint NOT NULL,
    vol_avg_multiple numeric(10,2) NOT NULL,
    price_volatility numeric(10,4) NOT NULL,
    scaler_score numeric(10,4) NOT NULL,
    is_selected boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    morning_return numeric(10,4),
    close_position numeric(5,4)
);


--
-- Name: TABLE stock_filter_score; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stock_filter_score IS '코스피 100 종목 스코어링 결과 (매일 갱신)';


--
-- Name: COLUMN stock_filter_score.morning_return; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_filter_score.morning_return IS '장초반 수익률';


--
-- Name: COLUMN stock_filter_score.close_position; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_filter_score.close_position IS '종가 위치 (0~1)';


--
-- Name: stock_filter_score_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_filter_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_filter_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_financial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_financial (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    base_date date NOT NULL,
    per numeric(10,2),
    roe numeric(10,2),
    operating_margin numeric(10,2),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE stock_financial; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stock_financial IS 'DART API 재무지표 (분기별 수집)';


--
-- Name: stock_financial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_financial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_financial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_master; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_master (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    market character varying(20) DEFAULT 'KOSPI'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE stock_master; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stock_master IS '종목 마스터 카탈로그 (검색용)';


--
-- Name: COLUMN stock_master.stock_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_master.stock_code IS '종목 코드';


--
-- Name: COLUMN stock_master.stock_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_master.stock_name IS '종목명';


--
-- Name: COLUMN stock_master.market; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_master.market IS '시장 구분 (KOSPI/KOSDAQ 등)';


--
-- Name: stock_master_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_realtime_price; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_realtime_price (
    id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50),
    current_price bigint NOT NULL,
    change_amount bigint,
    change_rate numeric(6,2),
    volume bigint,
    high_price bigint,
    low_price bigint,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE stock_realtime_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stock_realtime_price IS '종목별 실시간 가격 정보 (캐시)';


--
-- Name: COLUMN stock_realtime_price.current_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_realtime_price.current_price IS '현재가';


--
-- Name: COLUMN stock_realtime_price.change_amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_realtime_price.change_amount IS '전일 대비 변화량';


--
-- Name: COLUMN stock_realtime_price.change_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stock_realtime_price.change_rate IS '전일 대비 변화율(%)';


--
-- Name: stock_realtime_price_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_realtime_price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_realtime_price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade_execution_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trade_execution_plan (
    id integer NOT NULL,
    execution_date date NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(100),
    trade_type character varying(4) NOT NULL,
    planned_quantity integer NOT NULL,
    reference_price bigint,
    estimated_amount bigint,
    gemini_reason text NOT NULL,
    gemini_rank integer NOT NULL,
    safety_filter_passed boolean NOT NULL,
    safety_filter_details jsonb,
    execution_status character varying(20) DEFAULT 'PENDING'::character varying,
    executed_at timestamp without time zone,
    execution_result jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: TABLE trade_execution_plan; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.trade_execution_plan IS 'Safety Filter 통과 후 실제 매매 계획 및 실행 결과';


--
-- Name: COLUMN trade_execution_plan.safety_filter_details; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_execution_plan.safety_filter_details IS '각 규칙별 검증 상세 내용 (JSONB)';


--
-- Name: COLUMN trade_execution_plan.execution_result; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_execution_plan.execution_result IS 'KIS API 응답 결과 (주문번호, 체결가 등)';


--
-- Name: trade_execution_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trade_execution_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_execution_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trade_history (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50) NOT NULL,
    order_type character varying(10) NOT NULL,
    quantity integer NOT NULL,
    order_price numeric(12,2) NOT NULL,
    ordered_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    order_number character varying(50),
    order_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    executed_price numeric(12,2),
    executed_quantity integer,
    executed_at timestamp without time zone
);


--
-- Name: TABLE trade_history; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.trade_history IS '주문 및 체결 이력 (자동매매/수동매매)';


--
-- Name: COLUMN trade_history.order_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.order_type IS '주문 유형 (BUY: 매수, SELL: 매도)';


--
-- Name: COLUMN trade_history.quantity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.quantity IS '주문 수량';


--
-- Name: COLUMN trade_history.order_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.order_price IS '주문 단가';


--
-- Name: COLUMN trade_history.ordered_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.ordered_at IS '주문 시각';


--
-- Name: COLUMN trade_history.order_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.order_number IS 'KIS API 주문번호 (ODNO)';


--
-- Name: COLUMN trade_history.order_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.order_status IS '주문 상태 (PENDING: 접수, EXECUTED: 체결, CANCELLED: 취소, FAILED: 실패)';


--
-- Name: COLUMN trade_history.executed_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.executed_price IS '체결 단가';


--
-- Name: COLUMN trade_history.executed_quantity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.executed_quantity IS '체결 수량';


--
-- Name: COLUMN trade_history.executed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trade_history.executed_at IS '체결 시각';


--
-- Name: trade_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trade_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorites (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE user_favorites; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_favorites IS '사용자별 관심 종목';


--
-- Name: COLUMN user_favorites.user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_favorites.user_id IS '사용자 ID (FK)';


--
-- Name: COLUMN user_favorites.stock_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_favorites.stock_code IS '종목 코드';


--
-- Name: COLUMN user_favorites.stock_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_favorites.stock_name IS '종목명 (표시용 비정규화)';


--
-- Name: user_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_holdings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_holdings (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    stock_name character varying(50),
    quantity integer NOT NULL,
    avg_price bigint,
    current_price bigint,
    profit_loss bigint,
    profit_loss_rate numeric(6,2),
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE user_holdings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_holdings IS '사용자별 보유 종목 현황';


--
-- Name: COLUMN user_holdings.avg_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_holdings.avg_price IS '평균 매입가';


--
-- Name: COLUMN user_holdings.current_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_holdings.current_price IS '현재가';


--
-- Name: COLUMN user_holdings.profit_loss; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_holdings.profit_loss IS '평가 손익 (현재가 - 평균매입가) * 수량';


--
-- Name: COLUMN user_holdings.profit_loss_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_holdings.profit_loss_rate IS '평가 손익률(%)';


--
-- Name: user_holdings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_holdings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_holdings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_kis_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_kis_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    account_number character varying(50) NOT NULL,
    app_key character varying(255) NOT NULL,
    app_secret character varying(255) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    account_product_code character varying(10) DEFAULT '01'::character varying NOT NULL
);


--
-- Name: TABLE user_kis_accounts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_kis_accounts IS '사용자별 한국투자증권 API 키 및 계좌번호 (Jasypt 암호화 저장)';


--
-- Name: COLUMN user_kis_accounts.account_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_kis_accounts.account_number IS 'KIS 계좌번호 (8자리)';


--
-- Name: COLUMN user_kis_accounts.app_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_kis_accounts.app_key IS 'KIS APP Key (Jasypt 암호화 저장)';


--
-- Name: COLUMN user_kis_accounts.app_secret; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_kis_accounts.app_secret IS 'KIS APP Secret (Jasypt 암호화 저장)';


--
-- Name: COLUMN user_kis_accounts.is_verified; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_kis_accounts.is_verified IS 'KIS API 연동 검증 완료 여부';


--
-- Name: COLUMN user_kis_accounts.account_product_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_kis_accounts.account_product_code IS 'KIS 계좌상품코드 (기본값: 01)';


--
-- Name: user_kis_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_kis_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_kis_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_settings (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    asset_order jsonb DEFAULT '[{"key": "stocks_overseas", "icon": "📈", "label": "주식 (해외)"}, {"key": "stocks_domestic", "icon": "🏠", "label": "주식 (국내)"}, {"key": "coins", "icon": "🪙", "label": "코인"}, {"key": "bonds", "icon": "📜", "label": "채권"}]'::jsonb,
    dark_mode boolean DEFAULT false NOT NULL,
    auto_login boolean DEFAULT false NOT NULL,
    notifications jsonb DEFAULT '{"coins": {"news": true, "trading": true}, "stocks": {"news": true, "trading": true}}'::jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE user_settings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_settings IS '사용자별 UI 설정 정보';


--
-- Name: COLUMN user_settings.user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_settings.user_id IS '사용자 ID (FK)';


--
-- Name: COLUMN user_settings.asset_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_settings.asset_order IS '관심 자산 표시 순서 (드래그앤드롭)';


--
-- Name: COLUMN user_settings.dark_mode; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_settings.dark_mode IS '다크 모드 활성화 여부';


--
-- Name: COLUMN user_settings.auto_login; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_settings.auto_login IS '자동 로그인 설정';


--
-- Name: COLUMN user_settings.notifications; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_settings.notifications IS '알림 설정 (주식/코인 뉴스/매매)';


--
-- Name: user_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_trade_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_trade_config (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    order_amount bigint DEFAULT 1000000 NOT NULL,
    max_holdings integer DEFAULT 10 NOT NULL,
    order_type character varying(20) DEFAULT 'market'::character varying NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE user_trade_config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.user_trade_config IS '사용자별 자동매매 설정';


--
-- Name: COLUMN user_trade_config.order_amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_trade_config.order_amount IS '1회 주문 금액 (원)';


--
-- Name: COLUMN user_trade_config.max_holdings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_trade_config.max_holdings IS '최대 보유 종목 수';


--
-- Name: COLUMN user_trade_config.order_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_trade_config.order_type IS '주문 유형 (market: 시장가, limit: 지정가)';


--
-- Name: COLUMN user_trade_config.is_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_trade_config.is_active IS '자동매매 활성화 여부 (ON/OFF)';


--
-- Name: user_trade_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_trade_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_trade_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    phone character varying(20),
    birth_date date,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS '사용자 기본 정보 (회원가입 지원)';


--
-- Name: COLUMN users.username; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.username IS '로그인 ID';


--
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.email IS '이메일';


--
-- Name: COLUMN users.password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.password IS 'BCrypt 암호화된 비밀번호';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v_decision_with_filter; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_decision_with_filter AS
 SELECT d.decision_date,
    d.stock_code,
    d.decision,
    d.reason AS gemini_reason,
    d.rank AS gemini_rank,
    f.passed AS safety_passed,
    f.failure_reason,
    f.filter_checks,
    f.max_quantity,
    f.current_price
   FROM (public.ai_trade_decision d
     LEFT JOIN public.safety_filter_result f ON ((((d.stock_code)::text = (f.stock_code)::text) AND (d.decision_date = f.filter_date))))
  WHERE (d.decision_date >= (CURRENT_DATE - '7 days'::interval))
  ORDER BY d.decision_date DESC, d.rank;


--
-- Name: v_latest_trade_plan; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_latest_trade_plan AS
 SELECT execution_date,
    trade_type,
    count(*) AS plan_count,
    sum(
        CASE
            WHEN safety_filter_passed THEN 1
            ELSE 0
        END) AS passed_count,
    sum(
        CASE
            WHEN ((execution_status)::text = 'EXECUTED'::text) THEN 1
            ELSE 0
        END) AS executed_count,
    sum(estimated_amount) AS total_estimated_amount
   FROM public.trade_execution_plan
  WHERE (execution_date = CURRENT_DATE)
  GROUP BY execution_date, trade_type;


--
-- Name: v_market_overview; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_market_overview AS
 SELECT summary_date,
    kospi_index,
    kospi_change_rate,
    kospi_volume,
    total_stocks,
    rising_stocks,
    falling_stocks,
    unchanged_stocks,
    total_foreign_net_buy,
    total_institutional_net_buy,
    market_sentiment_score,
    ( SELECT count(*) AS count
           FROM public.ai_trade_decision
          WHERE ((ai_trade_decision.decision_date = mds.summary_date) AND ((ai_trade_decision.decision)::text = 'buy'::text))) AS buy_signals,
    ( SELECT count(*) AS count
           FROM public.ai_trade_decision
          WHERE ((ai_trade_decision.decision_date = mds.summary_date) AND ((ai_trade_decision.decision)::text = 'sell'::text))) AS sell_signals,
    ( SELECT count(*) AS count
           FROM public.safety_filter_result
          WHERE ((safety_filter_result.filter_date = mds.summary_date) AND (safety_filter_result.passed = true))) AS safety_passed_count,
    ( SELECT count(*) AS count
           FROM public.trade_execution_plan
          WHERE ((trade_execution_plan.execution_date = mds.summary_date) AND ((trade_execution_plan.execution_status)::text = 'EXECUTED'::text))) AS executed_trades
   FROM public.market_daily_summary mds
  ORDER BY summary_date DESC;


--
-- Name: v_stock_analysis_summary; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_stock_analysis_summary AS
 SELECT sfs.stock_code,
    sfs.stock_name,
    sfs.score_date,
    sfs.scaler_score,
    sfs.foreign_net_buy,
    sfs.institutional_net_buy,
    sfs.morning_return,
    sfs.close_position,
    sf.per,
    sf.roe,
    sf.operating_margin,
    na.sentiment_score,
    na.news_count,
    pf.price_trend,
    pf.volume_trend,
    pf.price_uncertainty,
    pf.yhat_d1,
    pf.yhat_d5,
    srp.current_price,
    srp.change_rate,
    atd.decision,
    atd.reason AS ai_reason,
    atd.rank AS ai_rank,
    sfr.passed AS safety_passed,
    sfr.failure_reason
   FROM ((((((public.stock_filter_score sfs
     LEFT JOIN public.stock_financial sf ON ((((sfs.stock_code)::text = (sf.stock_code)::text) AND (sf.base_date = ( SELECT max(stock_financial.base_date) AS max
           FROM public.stock_financial
          WHERE ((stock_financial.stock_code)::text = (sf.stock_code)::text))))))
     LEFT JOIN public.news_analysis na ON ((((sfs.stock_code)::text = (na.stock_code)::text) AND (sfs.score_date = na.analysis_date))))
     LEFT JOIN public.prophet_forecast pf ON ((((sfs.stock_code)::text = (pf.stock_code)::text) AND (sfs.score_date = pf.forecast_date))))
     LEFT JOIN public.stock_realtime_price srp ON (((sfs.stock_code)::text = (srp.stock_code)::text)))
     LEFT JOIN public.ai_trade_decision atd ON ((((sfs.stock_code)::text = (atd.stock_code)::text) AND (sfs.score_date = atd.decision_date))))
     LEFT JOIN public.safety_filter_result sfr ON ((((sfs.stock_code)::text = (sfr.stock_code)::text) AND (sfs.score_date = sfr.filter_date))))
  WHERE (sfs.is_selected = true);


--
-- Name: ai_trade_decision ai_trade_decision_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_trade_decision
    ADD CONSTRAINT ai_trade_decision_pkey PRIMARY KEY (id);


--
-- Name: ai_trade_decision ai_trade_decision_stock_code_decision_date_decision_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_trade_decision
    ADD CONSTRAINT ai_trade_decision_stock_code_decision_date_decision_key UNIQUE (stock_code, decision_date, decision);


--
-- Name: feature_threshold_config feature_threshold_config_feature_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_threshold_config
    ADD CONSTRAINT feature_threshold_config_feature_name_key UNIQUE (feature_name);


--
-- Name: feature_threshold_config feature_threshold_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_threshold_config
    ADD CONSTRAINT feature_threshold_config_pkey PRIMARY KEY (id);


--
-- Name: market_daily_summary market_daily_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_daily_summary
    ADD CONSTRAINT market_daily_summary_pkey PRIMARY KEY (id);


--
-- Name: market_daily_summary market_daily_summary_summary_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_daily_summary
    ADD CONSTRAINT market_daily_summary_summary_date_key UNIQUE (summary_date);


--
-- Name: news_analysis news_analysis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_analysis
    ADD CONSTRAINT news_analysis_pkey PRIMARY KEY (id);


--
-- Name: news_analysis news_analysis_stock_code_analysis_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_analysis
    ADD CONSTRAINT news_analysis_stock_code_analysis_date_key UNIQUE (stock_code, analysis_date);


--
-- Name: prophet_forecast prophet_forecast_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prophet_forecast
    ADD CONSTRAINT prophet_forecast_pkey PRIMARY KEY (id);


--
-- Name: prophet_forecast prophet_forecast_stock_code_forecast_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prophet_forecast
    ADD CONSTRAINT prophet_forecast_stock_code_forecast_date_key UNIQUE (stock_code, forecast_date);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- Name: safety_filter_result safety_filter_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_filter_result
    ADD CONSTRAINT safety_filter_result_pkey PRIMARY KEY (id);


--
-- Name: stock_filter_score stock_filter_score_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_filter_score
    ADD CONSTRAINT stock_filter_score_pkey PRIMARY KEY (id);


--
-- Name: stock_filter_score stock_filter_score_stock_code_score_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_filter_score
    ADD CONSTRAINT stock_filter_score_stock_code_score_date_key UNIQUE (stock_code, score_date);


--
-- Name: stock_financial stock_financial_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_financial
    ADD CONSTRAINT stock_financial_pkey PRIMARY KEY (id);


--
-- Name: stock_financial stock_financial_stock_code_base_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_financial
    ADD CONSTRAINT stock_financial_stock_code_base_date_key UNIQUE (stock_code, base_date);


--
-- Name: stock_master stock_master_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_master
    ADD CONSTRAINT stock_master_pkey PRIMARY KEY (id);


--
-- Name: stock_master stock_master_stock_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_master
    ADD CONSTRAINT stock_master_stock_code_key UNIQUE (stock_code);


--
-- Name: stock_realtime_price stock_realtime_price_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_realtime_price
    ADD CONSTRAINT stock_realtime_price_pkey PRIMARY KEY (id);


--
-- Name: stock_realtime_price stock_realtime_price_stock_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_realtime_price
    ADD CONSTRAINT stock_realtime_price_stock_code_key UNIQUE (stock_code);


--
-- Name: trade_execution_plan trade_execution_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_execution_plan
    ADD CONSTRAINT trade_execution_plan_pkey PRIMARY KEY (id);


--
-- Name: trade_history trade_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_history
    ADD CONSTRAINT trade_history_pkey PRIMARY KEY (id);


--
-- Name: safety_filter_result uk_safety_filter_date_stock; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_filter_result
    ADD CONSTRAINT uk_safety_filter_date_stock UNIQUE (filter_date, stock_code);


--
-- Name: user_favorites uk_user_favorites_user_stock; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT uk_user_favorites_user_stock UNIQUE (user_id, stock_code);


--
-- Name: user_holdings uk_user_holdings_user_stock; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_holdings
    ADD CONSTRAINT uk_user_holdings_user_stock UNIQUE (user_id, stock_code);


--
-- Name: trade_execution_plan unique_execution_plan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_execution_plan
    ADD CONSTRAINT unique_execution_plan_key UNIQUE (execution_date, stock_code, trade_type);


--
-- Name: user_favorites user_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT user_favorites_pkey PRIMARY KEY (id);


--
-- Name: user_holdings user_holdings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_holdings
    ADD CONSTRAINT user_holdings_pkey PRIMARY KEY (id);


--
-- Name: user_kis_accounts user_kis_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_kis_accounts
    ADD CONSTRAINT user_kis_accounts_pkey PRIMARY KEY (id);


--
-- Name: user_kis_accounts user_kis_accounts_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_kis_accounts
    ADD CONSTRAINT user_kis_accounts_user_id_key UNIQUE (user_id);


--
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (id);


--
-- Name: user_settings user_settings_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_user_id_key UNIQUE (user_id);


--
-- Name: user_trade_config user_trade_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trade_config
    ADD CONSTRAINT user_trade_config_pkey PRIMARY KEY (id);


--
-- Name: user_trade_config user_trade_config_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trade_config
    ADD CONSTRAINT user_trade_config_user_id_key UNIQUE (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_ai_decision_date_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_decision_date_type ON public.ai_trade_decision USING btree (decision_date DESC, decision);


--
-- Name: idx_ai_decision_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_decision_stock ON public.ai_trade_decision USING btree (stock_code, decision_date DESC);


--
-- Name: idx_ai_trade_decision_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trade_decision_code ON public.ai_trade_decision USING btree (stock_code, decision_date);


--
-- Name: idx_ai_trade_decision_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trade_decision_date ON public.ai_trade_decision USING btree (decision_date);


--
-- Name: idx_ai_trade_decision_rank; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trade_decision_rank ON public.ai_trade_decision USING btree (decision_date, decision, rank);


--
-- Name: idx_execution_plan_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_execution_plan_date ON public.trade_execution_plan USING btree (execution_date DESC);


--
-- Name: idx_execution_plan_date_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_execution_plan_date_stock ON public.trade_execution_plan USING btree (execution_date, stock_code);


--
-- Name: idx_execution_plan_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_execution_plan_status ON public.trade_execution_plan USING btree (execution_status);


--
-- Name: idx_market_summary_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_market_summary_date ON public.market_daily_summary USING btree (summary_date DESC);


--
-- Name: idx_news_analysis_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_news_analysis_date ON public.news_analysis USING btree (analysis_date);


--
-- Name: idx_news_analysis_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_news_analysis_stock ON public.news_analysis USING btree (stock_code, analysis_date);


--
-- Name: idx_prophet_forecast_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prophet_forecast_code ON public.prophet_forecast USING btree (stock_code);


--
-- Name: idx_prophet_forecast_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prophet_forecast_date ON public.prophet_forecast USING btree (forecast_date);


--
-- Name: idx_realtime_price_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_realtime_price_code ON public.stock_realtime_price USING btree (stock_code);


--
-- Name: idx_realtime_price_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_realtime_price_updated ON public.stock_realtime_price USING btree (updated_at DESC);


--
-- Name: idx_refresh_tokens_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token);


--
-- Name: idx_refresh_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_user ON public.refresh_tokens USING btree (user_id);


--
-- Name: idx_safety_filter_date_passed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_safety_filter_date_passed ON public.safety_filter_result USING btree (filter_date DESC, passed);


--
-- Name: idx_safety_filter_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_safety_filter_stock ON public.safety_filter_result USING btree (stock_code, filter_date DESC);


--
-- Name: idx_stock_filter_score_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_filter_score_date ON public.stock_filter_score USING btree (score_date);


--
-- Name: idx_stock_filter_score_selected; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_filter_score_selected ON public.stock_filter_score USING btree (score_date, is_selected);


--
-- Name: idx_stock_financial_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_financial_code ON public.stock_financial USING btree (stock_code);


--
-- Name: idx_stock_financial_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_financial_date ON public.stock_financial USING btree (base_date);


--
-- Name: idx_stock_master_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_master_code ON public.stock_master USING btree (stock_code);


--
-- Name: idx_stock_master_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_master_name ON public.stock_master USING btree (stock_name);


--
-- Name: idx_trade_history_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_history_date ON public.trade_history USING btree (ordered_at);


--
-- Name: idx_trade_history_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_history_status ON public.trade_history USING btree (order_status);


--
-- Name: idx_trade_history_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_history_stock ON public.trade_history USING btree (stock_code);


--
-- Name: idx_trade_history_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_history_user ON public.trade_history USING btree (user_id);


--
-- Name: idx_user_favorites_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_favorites_user ON public.user_favorites USING btree (user_id);


--
-- Name: idx_user_holdings_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_holdings_stock ON public.user_holdings USING btree (stock_code);


--
-- Name: idx_user_holdings_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_holdings_user ON public.user_holdings USING btree (user_id);


--
-- Name: idx_user_kis_accounts_account; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_kis_accounts_account ON public.user_kis_accounts USING btree (account_number);


--
-- Name: idx_user_kis_accounts_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_kis_accounts_user ON public.user_kis_accounts USING btree (user_id);


--
-- Name: idx_user_settings_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_settings_user_id ON public.user_settings USING btree (user_id);


--
-- Name: idx_user_trade_config_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_trade_config_user ON public.user_trade_config USING btree (user_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_username ON public.users USING btree (username);


--
-- Name: refresh_tokens fk_refresh_tokens_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: trade_history fk_trade_history_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_history
    ADD CONSTRAINT fk_trade_history_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_favorites fk_user_favorites_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT fk_user_favorites_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_holdings fk_user_holdings_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_holdings
    ADD CONSTRAINT fk_user_holdings_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_kis_accounts fk_user_kis_accounts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_kis_accounts
    ADD CONSTRAINT fk_user_kis_accounts_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_settings fk_user_settings_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT fk_user_settings_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_trade_config fk_user_trade_config_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trade_config
    ADD CONSTRAINT fk_user_trade_config_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict GiVCyOciIMcYY1xDyKq1bvB8cUdwqOIQUnYCVWQMVfGNZtkkUH5az1TBtuHb5go

